### ISSUE TITLE
Please consider controlling Debugging from configuration or environment

### ISSUE THREAD

**Issue by Zugschlus** [ThomasNoll/oas#5]
Hi,

setting -DDEBUG at compile time is a bit clumsy when using oas from a distribution package. Please consider supporting an OAS_DEBUG environment variable or a configuration file option instead. I guess that having OAS_DEBUG is reasonably easy to implement.

Greetings
Marc

**Comment by ThomasNoll** [comment]
Implemented as OAS_LOGLEVEL env var.
